version: '3.8'

services:

  api:
    container_name: API
    build:
      context: ./
      dockerfile: docker/node/Dockerfile
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
    env_file:
      - ./.dotenv_files/.env.development.local
    #   depends_on:
    #     - db

  db:
    container_name: Database
    image: postgres:13-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres/data:/var/lib/postgres/data/
    env_file:
      - ./.dotenv_files/.env.development.local
